version: "3.9"
services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile # hoặc dùng image có sẵn
    volumes:
      - ..:/workspaces:cached
    command: sleep infinity
    depends_on:
      - db
    # Chạy dev bên trong container app
    ports:
      - "3000:3000" # Frontend
      - "8080:8080" # Backend
    env_file:
      - ../apps/backend/.env
    # Đặt tên network chung để app ↔ db giao tiếp
    networks:
      - devnet

  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../apps/database/migrations/init_official.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    ports:
      - "5432:5432" # tuỳ chọn: expose ra host (dành cho công cụ ngoài VS Code)
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d appdb" ]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - devnet

volumes:
  pgdata:


networks:
  devnet:
    driver: bridge
